name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2618888f9f39dd743e2d5db1c904da73cb5eafd635a1bf4a82b9c0c6c6ee6914"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
