name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8297369a6d736746aae7092632d0a1cc57743267a5d4e085dbf9b5b1ca7bdd5c"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
