name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a9da9fe177626b3fa2a1ce4a8059aab3a982929ab0a5cbfd69d8ee90a4b2338"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
