name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd87d0c874a5adb0e9770be8c236d4ff620b76e8eb85c4e5c315280625dbc734"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
