name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "615d93c519f344ed1edacfcdecafe01cf0001d288d4b11e273eadcc00ca4b5ba"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
