name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "423148a9003295f34adbf4895ca2e4527f132c548c7c3fd49b37f518b9095749"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
