name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "345f451e2dc0f278ae84a81254d5c88098a23e974d2c9dec9fc57d32a4e69092"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
