name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ac3f3b4a015094340ab3ab546f2d90e5fe8685dce8121008e27b37daae2f2f3"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
