name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "492297d66f5fa102bdd0b0710d1a912b55134676c28aae93bf351f5c75c361aa"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
