name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bcf0d4907f19a755ab79b2bb104dd4fcb4e12edb5edf0b858a250b50c84ff71"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
