name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d723b8ebf0f70fad1d7a04a37e254e49883adcd157ef78bdd5487f18ff0d25e5"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
