name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d38642148b47a47fd47508289ca025191cac45f10ec446f611afea9b15442301"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
