name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa5336155afbb6506f86d6dba469282c41864a5a5fe219ecc231bfd0881bf993"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
