name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e44a5cb2bdb3270fa2f2319b63dca724a39901ae5615c04f8a4d0599083c6d55"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
