name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c092697ddb0500bd0955f9a84858ddce1afbdf93c70d1395e20f6e84f0f18eb9"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
