name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef5f0249ec66d11b60b3f76c0402555943070cd4b137632c99b51f726bee0493"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
