name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2615b082a15cb16c3541570c19295ae03f2471b66ec1b62aa811a7c2c2c326a"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
