name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9004ad4956835dcd4b038e860cfb5132fc96801e5e831ad79bfd4ef674c9e756"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
