name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bedd971bd3d6371ce1092ce63e03a281bef30b11f58f50cd6e2a6b975c345a68"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
