name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cc65e363889f18053dea8c29e59fc13230c7e7a6714c690e1b2d3745f2efe22"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
