name = "MeowcorpSMP G2"
author = "Meowcorp Group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3d222b73777d4ad93fb9df10a96a8e52be06504ea0433cbeef7232dd14b12a1"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
